version: "3.9"
    
services:
    uts-backend:
        build: 
            context: ./rest-api
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - uts-mysql-db
        ports:
            - 8080:8080
        volumes: 
            - uts-backend-target:/app/target


    uts-mysql-db:
        image: mysql:5.7
        platform: linux/x86_64
        volumes:
            - uts-mysql-db-data:/var/lib/mysql
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_HOST: localhost
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: UniversityTransportSystem
    
volumes:
    uts-mysql-db-data: {}
    uts-backend-target: {}
